### ISSUE TITLE
Two question

### ISSUE THREAD

**Issue by jackpaster** [jamesdouble/JDBreaksLoading#1]
@jamesdouble Love this project. I'm going to have it so that when a user presses a button this activity loader will pop up. What code would I put in the sender:any object to present the loader and second, I want this loader to dismiss once everything was sent to the server, how can I do that instead of declaring a single value for the time that the loader will be presented.

**Comment by jamesdouble** [comment]
For now, You can declare a Global variable for JDBreaksLoading, 
I will try to make it easier to show and dismiss later

**Comment by jamesdouble** [comment]
HI @jackpaster , I have a new repo https://github.com/jamesdouble/JDGamesLoading here.
It contains BreakLoading , and may have resolved your issue.
