### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [jamesdouble/JDBreaksLoading#3]
Hey @jamesdouble, your lib is awesome but your README lacks information.
I created this [iOS README template](https://github.com/awesome-labs/iOS-readme-template) to help you out 😉 

I'd be cool to also add Cocoapods support. I've done this implementation myself last week for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

Please fix these issues before we can approve [the AwesomeiOS PR](https://github.com/vsouza/awesome-ios/pull/1995)

**Comment by jamesdouble** [comment]
@lfarah 
Sorry for waiting.
I have update my README.
